local require = require(script.Parent.loader).load(script)
local Jest = require("Jest")
local describe, expect, it = Jest.Globals.describe, Jest.Globals.expect, Jest.Globals.it
local cancellableDelay = require("cancellableDelay")
local CancelToken = require("CancelToken")
local Maid = require("Maid")
local Rx = require("Rx")
local Observable = require("Observable")
local function open(...) local a = table.pack(...) return Observable.new(function(sub) for i = 1, a.n do sub:Fire(a[i]) end end) end
local Brio = require("Brio")
local Promise = require("Promise")
local ThrottledFunction = require("ThrottledFunction")

describe("scheduler-dependent behaviours under Lune real task lib", function()
	it("cancellableDelay fires when not cancelled", function()
		local fired = false
		cancellableDelay(0.02, function() fired = true end)
		task.wait(0.06)
		expect(fired).toBe(true)
	end)
	it("cancellableDelay: cancel closes a thread parked in task.wait", function()
		local fired = false
		local cancel = cancellableDelay(0.02, function() fired = true end)
		cancel()
		task.wait(0.06) -- Lune scheduler would resume the closed thread here
		expect(fired).toBe(false)
	end)
	it("CancelToken.fromSeconds cancels via task.delay thread", function()
		local token = CancelToken.fromSeconds(0.02)
		expect(token:IsCancelled()).toBe(false)
		task.wait(0.06)
		expect(token:IsCancelled()).toBe(true)
	end)
	it("CancelToken.fromSeconds then maid cancel stops the delay thread", function()
		local maid = Maid.new()
		local token = CancelToken.fromMaid(maid)
		maid:DoCleaning()
		expect(token:IsCancelled()).toBe(true)
	end)
	it("Rx.delayed emits once", function()
		local n = 0
		local sub = Rx.delayed(0.02):Subscribe(function() n += 1 end)
		task.wait(0.06)
		expect(n).toBe(1)
		sub:Destroy()
	end)
	it("Rx.delayed destroyed early does not emit", function()
		local n = 0
		local sub = Rx.delayed(0.02):Subscribe(function() n += 1 end)
		sub:Destroy()
		task.wait(0.06)
		expect(n).toBe(0)
	end)
	it("Rx.timer ticks and Destroy cancels the spawned loop thread", function()
		local n = 0
		local sub = Rx.timer(0, 0.02):Subscribe(function() n += 1 end)
		task.wait(0.07)
		sub:Destroy()
		local after = n
		task.wait(0.06)
		expect(n >= 2).toBe(true)
		expect(n).toBe(after)
	end)
	it("Rx.delay (cancellableDelay) emits then destroyed early drops", function()
		local got = {}
		local sub = open(1):Pipe({ Rx.delay(0.02) }):Subscribe(function(v) table.insert(got, v) end)
		task.wait(0.06)
		expect(got[1]).toBe(1)
		sub:Destroy()
	end)
	it("Rx.throttleDefer + onlyAfterDefer use task.defer", function()
		local got = {}
		local sub = open(1, 2, 3):Pipe({ Rx.throttleDefer() }):Subscribe(function(v) table.insert(got, v) end)
		task.wait(0.02)
		expect(#got).toBe(1)
		expect(got[1]).toBe(3)
		sub:Destroy()
	end)
	it("Rx.fromPromise with delayed promise", function()
		local out
		local p = Promise.delay(0.02, function(resolve) resolve("x") end)
		local sub = Rx.fromPromise(p):Subscribe(function(v) out = v end)
		task.wait(0.06)
		expect(out).toBe("x")
		sub:Destroy()
	end)
	it("Rx.toPromise yields", function()
		local p = Rx.toPromise(Rx.delayed(0.02))
		local ok = p:Yield()
		expect(ok).toBe(true)
	end)
	it("Brio.delayed kills after time", function()
		local b = Brio.delayed(0.02, "v")
		expect(b:IsDead()).toBe(false)
		task.wait(0.06)
		expect(b:IsDead()).toBe(true)
	end)
	it("ThrottledFunction trailing via task.delay/task.cancel", function()
		local calls = {}
		local tf = ThrottledFunction.new(0.03, function(v) table.insert(calls, v) end)
		tf:Call(1); tf:Call(2); tf:Call(3)
		expect(#calls).toBe(1)
		task.wait(0.08)
		expect(calls[2]).toBe(3)
		tf:Destroy()
	end)
end)
